#!/usr/bin/env python3
"""Vela audit pass 3: series split + fee/PnL invariants.

Consumes the parquet and `outcomes.json` generated by the prior workflow steps.
No additional network calls.
"""
from __future__ import annotations

import json
import math
import os
from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path(os.environ.get("AUDIT_OUT", ".")).resolve()


def series_of(ticker: str) -> str:
    if ticker.startswith("KXBTC15M-"):
        return "KXBTC15M"
    if ticker.startswith("KXBTCD-"):
        return "KXBTCD"
    return ticker.split("-", 1)[0]


def maker_fee(qty: int, p: float) -> float:
    return math.ceil(0.0175 * qty * p * (1-p) * 100 - 1e-12) / 100.0


def gross(qty: int, p: float, won: bool) -> float:
    return qty * (1-p) if won else -qty * p


def solve_qty(net: float, p: float, won: bool, max_qty: int, mode: str, tol=1e-8):
    matches=[]
    for q in range(1, max_qty+1):
        pred=gross(q,p,won)
        if mode=="maker0175":
            pred-=maker_fee(q,p)
        if abs(pred-net)<=tol:
            matches.append(q)
    return matches


def main():
    df=pd.read_parquet(OUT/"fill_calibration_btc.parquet")
    outcomes=json.loads((OUT/"outcomes.json").read_text(encoding="utf-8"))
    api=pd.DataFrame([v for v in outcomes.values() if v.get("ok") and v.get("result") in ("yes","no")])
    m=df.merge(api[["ticker","result"]],on="ticker",how="left")
    m["api_won"]=(m.result==m.side).astype(float)
    m["series"]=m.ticker.map(series_of)

    per_series={}
    for ser,g in m.groupby("series"):
        f=g[g.filled==1]; u=g[g.filled==0]
        per_series[ser]={
            "attempts":len(g),"filled":int(g.filled.sum()),"fill_rate":float(g.filled.mean()),
            "filled_wins":int(f.api_won.sum()),"filled_losses":int(len(f)-f.api_won.sum()),
            "filled_win_rate":float(f.api_won.mean()) if len(f) else None,
            "unfilled_wins":int(u.api_won.sum()),"unfilled_losses":int(len(u)-u.api_won.sum()),
            "unfilled_win_rate":float(u.api_won.mean()) if len(u) else None,
            "mean_p_filled":float(f.p_side.mean()) if len(f) else None,
            "mean_p_unfilled":float(u.p_side.mean()) if len(u) else None,
            "pnl_sum":float(f.net_pnl.sum()) if len(f) else 0.0,
            "pnl_mean":float(f.net_pnl.mean()) if len(f) else None,
            "pnl_win_sum":float(f.loc[f.api_won==1,"net_pnl"].sum()) if len(f) else 0.0,
            "pnl_loss_sum":float(f.loc[f.api_won==0,"net_pnl"].sum()) if len(f) else 0.0,
        }

    losses=m[(m.filled==1)&(m.api_won==0)][
        ["ticker","series","side","p_side","contracts","our_bid","fill_px","net_pnl","time_to_close"]
    ].sort_values("net_pnl").to_dict("records")

    # Strict arithmetic subset: reported first fill price equals the logged order price.
    f=m[m.filled==1].copy()
    strict=f[np.isclose(f.fill_px,f.our_bid,atol=1e-12)].copy()
    rows=[]
    z_plaus=mf_plaus=both=neither=0
    z_full=mf_full=0
    for _,r in strict.iterrows():
        maxq=int(round(float(r.contracts)))
        won=bool(r.api_won)
        z=solve_qty(float(r.net_pnl),float(r.fill_px),won,maxq,"zero")
        mf=solve_qty(float(r.net_pnl),float(r.fill_px),won,maxq,"maker0175")
        if z: z_plaus+=1
        if mf: mf_plaus+=1
        if z and mf: both+=1
        if not z and not mf: neither+=1
        if maxq in z: z_full+=1
        if maxq in mf: mf_full+=1
        rows.append({"ticker":r.ticker,"series":r.series,"won":int(won),"submitted":maxq,
                     "price":float(r.fill_px),"reported_net":float(r.net_pnl),
                     "zero_fee_qty_matches":z,"maker0175_qty_matches":mf,
                     "gross_full":gross(maxq,float(r.fill_px),won),
                     "maker0175_fee_full":maker_fee(maxq,float(r.fill_px)),
                     "maker0175_net_full":gross(maxq,float(r.fill_px),won)-maker_fee(maxq,float(r.fill_px))})
    fee_diag={
        "strict_rows_fill_px_equals_our_bid":len(strict),
        "zero_fee_has_some_qty_solution_le_submitted":z_plaus,
        "maker0175_has_some_qty_solution_le_submitted":mf_plaus,
        "both_models_match_some_qty":both,
        "neither_model_matches":neither,
        "zero_fee_full_submitted_qty_exact":z_full,
        "maker0175_full_submitted_qty_exact":mf_full,
        "rows":rows,
    }

    # Aggregation signatures: averaged resting placements should create sub-cent bids.
    agg={
      "all_rows":len(m),
      "our_bid_not_cent_aligned":int((np.abs(m.our_bid*100-np.round(m.our_bid*100))>1e-8).sum()),
      "filled_rows":len(f),
      "fill_above_logged_limit":int((f.fill_px>f.our_bid+1e-12).sum()),
      "fill_equal_logged_limit":int(np.isclose(f.fill_px,f.our_bid,atol=1e-12).sum()),
      "fill_below_logged_limit":int((f.fill_px<f.our_bid-1e-12).sum()),
    }

    out={"per_series":per_series,"loss_rows":losses,"fee_diagnostic":fee_diag,"aggregation":agg}
    (OUT/"series_fee_audit.json").write_text(json.dumps(out,indent=2,sort_keys=True),encoding="utf-8")

    def pct(x): return "n/a" if x is None else f"{100*x:.3f}%"
    L=["# Vela series + fee audit","","## Series split"]
    for ser,s in per_series.items():
        L += [f"### {ser}",
              f"- attempts={s['attempts']}; fills={s['filled']} ({pct(s['fill_rate'])})",
              f"- filled={s['filled_wins']}W/{s['filled_losses']}L = {pct(s['filled_win_rate'])}; mean p={pct(s['mean_p_filled'])}",
              f"- unfilled={s['unfilled_wins']}W/{s['unfilled_losses']}L = {pct(s['unfilled_win_rate'])}; mean p={pct(s['mean_p_unfilled'])}",
              f"- filled PnL sum=${s['pnl_sum']:+.4f}; winner sum=${s['pnl_win_sum']:+.4f}; loser sum=${s['pnl_loss_sum']:+.4f}",""]
    L += ["## All filled losses"]
    for x in losses:
        L.append(f"- `{x['ticker']}` {x['series']} side={x['side']} p={pct(x['p_side'])} submitted={x['contracts']:.0f} bid={x['our_bid']:.3f} first_fill={x['fill_px']:.3f} PnL=${x['net_pnl']:+.4f} ttc={x['time_to_close']:.2f}s")
    L += ["","## Fee arithmetic on strict price-matched rows",
          f"- strict rows (`fill_px == our_bid`): **{len(strict)}**",
          f"- some integer qty <= submitted reproduces reported PnL with ZERO maker fee: **{z_plaus}/{len(strict)}**",
          f"- some integer qty <= submitted reproduces reported PnL with 0.0175 maker fee: **{mf_plaus}/{len(strict)}**",
          f"- full submitted qty exactly matches ZERO fee: **{z_full}/{len(strict)}**",
          f"- full submitted qty exactly matches 0.0175 maker fee: **{mf_full}/{len(strict)}**",
          f"- neither simple model: **{neither}/{len(strict)}** (multi-fill/aggregation/other accounting possible)","",
          "## Aggregation signatures",
          f"- non-cent `our_bid`: **{agg['our_bid_not_cent_aligned']}/{agg['all_rows']}**",
          f"- filled price above/equal/below logged buy limit: **{agg['fill_above_logged_limit']} / {agg['fill_equal_logged_limit']} / {agg['fill_below_logged_limit']}**"]
    (OUT/"series_fee_audit.md").write_text("\n".join(L)+"\n",encoding="utf-8")
    print("\n".join(L))

if __name__=="__main__": main()
